//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciBilgiK
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string İsim { get; set; }
        public string Soyisim { get; set; }
        public string TelefonNo { get; set; }
        public string Adres { get; set; }
        public string Cinsiyet { get; set; }
        public string Sifre { get; set; }
    }
}
