//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Veritabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DolabimWebEntity : DbContext
    {
        public DolabimWebEntity()
            : base("name=DolabimWebEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KullaniciBilgiK> KullaniciBilgiK { get; set; }
        public DbSet<SirketBilgiK> SirketBilgiK { get; set; }
        public DbSet<Tbl_Urun> Tbl_Urun { get; set; }
    }
}
