//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urun
    {
        public int Urun_Id { get; set; }
        public string UrunKategori { get; set; }
        public string UrunBeden { get; set; }
        public string UrunAdet { get; set; }
        public string UrunMarka { get; set; }
        public string UrunModel { get; set; }
        public string UrunFiyat { get; set; }
    }
}
